<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'apy_grid.registry' shared service.

include_once $this->targetDirs[3].'\\vendor\\apy\\datagrid-bundle\\Grid\\GridRegistryInterface.php';
include_once $this->targetDirs[3].'\\vendor\\apy\\datagrid-bundle\\Grid\\GridRegistry.php';
include_once $this->targetDirs[3].'\\vendor\\apy\\datagrid-bundle\\Grid\\GridTypeInterface.php';
include_once $this->targetDirs[3].'\\vendor\\apy\\datagrid-bundle\\Grid\\AbstractType.php';
include_once $this->targetDirs[3].'\\vendor\\apy\\datagrid-bundle\\Grid\\Type\\GridType.php';
include_once $this->targetDirs[3].'\\vendor\\apy\\datagrid-bundle\\Grid\\Column\\Column.php';
include_once $this->targetDirs[3].'\\vendor\\apy\\datagrid-bundle\\Grid\\Column\\TextColumn.php';
include_once $this->targetDirs[3].'\\vendor\\apy\\datagrid-bundle\\Grid\\Column\\ArrayColumn.php';
include_once $this->targetDirs[3].'\\vendor\\apy\\datagrid-bundle\\Grid\\Column\\BlankColumn.php';
include_once $this->targetDirs[3].'\\vendor\\apy\\datagrid-bundle\\Grid\\Column\\BooleanColumn.php';
include_once $this->targetDirs[3].'\\vendor\\apy\\datagrid-bundle\\Grid\\Column\\DateTimeColumn.php';
include_once $this->targetDirs[3].'\\vendor\\apy\\datagrid-bundle\\Grid\\Column\\DateColumn.php';
include_once $this->targetDirs[3].'\\vendor\\apy\\datagrid-bundle\\Grid\\Column\\JoinColumn.php';
include_once $this->targetDirs[3].'\\vendor\\apy\\datagrid-bundle\\Grid\\Column\\NumberColumn.php';
include_once $this->targetDirs[3].'\\vendor\\apy\\datagrid-bundle\\Grid\\Column\\RankColumn.php';
include_once $this->targetDirs[3].'\\vendor\\apy\\datagrid-bundle\\Grid\\Column\\TimeColumn.php';

$this->services['apy_grid.registry'] = $instance = new \APY\DataGridBundle\Grid\GridRegistry();

$instance->addType(${($_ = isset($this->services['apy_grid.type.grid']) ? $this->services['apy_grid.type.grid'] : $this->services['apy_grid.type.grid'] = new \APY\DataGridBundle\Grid\Type\GridType()) && false ?: '_'});
$instance->addColumn(${($_ = isset($this->services['apy_grid.column.text']) ? $this->services['apy_grid.column.text'] : $this->services['apy_grid.column.text'] = new \APY\DataGridBundle\Grid\Column\TextColumn()) && false ?: '_'});
$instance->addColumn(${($_ = isset($this->services['apy_grid.column.array']) ? $this->services['apy_grid.column.array'] : $this->services['apy_grid.column.array'] = new \APY\DataGridBundle\Grid\Column\ArrayColumn()) && false ?: '_'});
$instance->addColumn(${($_ = isset($this->services['apy_grid.column.blank']) ? $this->services['apy_grid.column.blank'] : $this->services['apy_grid.column.blank'] = new \APY\DataGridBundle\Grid\Column\BlankColumn()) && false ?: '_'});
$instance->addColumn(${($_ = isset($this->services['apy_grid.column.boolean']) ? $this->services['apy_grid.column.boolean'] : $this->services['apy_grid.column.boolean'] = new \APY\DataGridBundle\Grid\Column\BooleanColumn()) && false ?: '_'});
$instance->addColumn(${($_ = isset($this->services['apy_grid.column.date']) ? $this->services['apy_grid.column.date'] : $this->services['apy_grid.column.date'] = new \APY\DataGridBundle\Grid\Column\DateColumn()) && false ?: '_'});
$instance->addColumn(${($_ = isset($this->services['apy_grid.column.date_time']) ? $this->services['apy_grid.column.date_time'] : $this->services['apy_grid.column.date_time'] = new \APY\DataGridBundle\Grid\Column\DateTimeColumn()) && false ?: '_'});
$instance->addColumn(${($_ = isset($this->services['apy_grid.column.join']) ? $this->services['apy_grid.column.join'] : $this->services['apy_grid.column.join'] = new \APY\DataGridBundle\Grid\Column\JoinColumn()) && false ?: '_'});
$instance->addColumn(${($_ = isset($this->services['apy_grid.column.number']) ? $this->services['apy_grid.column.number'] : $this->services['apy_grid.column.number'] = new \APY\DataGridBundle\Grid\Column\NumberColumn()) && false ?: '_'});
$instance->addColumn(${($_ = isset($this->services['apy_grid.column.rank']) ? $this->services['apy_grid.column.rank'] : $this->services['apy_grid.column.rank'] = new \APY\DataGridBundle\Grid\Column\RankColumn()) && false ?: '_'});
$instance->addColumn(${($_ = isset($this->services['apy_grid.column.time']) ? $this->services['apy_grid.column.time'] : $this->services['apy_grid.column.time'] = new \APY\DataGridBundle\Grid\Column\TimeColumn()) && false ?: '_'});

return $instance;
