<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'vich_uploader.download_handler' shared service.

include_once $this->targetDirs[3].'\\vendor\\vich\\uploader-bundle\\Handler\\AbstractHandler.php';
include_once $this->targetDirs[3].'\\vendor\\vich\\uploader-bundle\\Handler\\DownloadHandler.php';

return $this->services['vich_uploader.download_handler'] = new \Vich\UploaderBundle\Handler\DownloadHandler(${($_ = isset($this->services['vich_uploader.property_mapping_factory']) ? $this->services['vich_uploader.property_mapping_factory'] : $this->getVichUploader_PropertyMappingFactoryService()) && false ?: '_'}, ${($_ = isset($this->services['vich_uploader.storage']) ? $this->services['vich_uploader.storage'] : $this->getVichUploader_StorageService()) && false ?: '_'});
