<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0abndpo\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0abndpo/appProdProjectContainer.php') {
    touch(__DIR__.'/Container0abndpo.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container0abndpo\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container0abndpo\appProdProjectContainer(array(
    'container.build_hash' => '0abndpo',
    'container.build_id' => '9084aec8',
    'container.build_time' => 1548826531,
), __DIR__.\DIRECTORY_SEPARATOR.'Container0abndpo');
