<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Invoice extends \AppBundle\Entity\Invoice implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'invoicedate', 'invoicenumber', 'company', 'address1', 'address2', 'city', 'pincode', 'state', 'statecode', 'mobile', 'gstin', 'subtotal', 'cgst', 'sgst', 'igst', 'cashdiscount', 'grandtotal', 'balance', 'inwords', 'status', 'cancel', 'paiddate', 'customer'];
        }

        return ['__isInitialized__', 'id', 'invoicedate', 'invoicenumber', 'company', 'address1', 'address2', 'city', 'pincode', 'state', 'statecode', 'mobile', 'gstin', 'subtotal', 'cgst', 'sgst', 'igst', 'cashdiscount', 'grandtotal', 'balance', 'inwords', 'status', 'cancel', 'paiddate', 'customer'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Invoice $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvoicedate($invoicedate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvoicedate', [$invoicedate]);

        return parent::setInvoicedate($invoicedate);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoicedate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoicedate', []);

        return parent::getInvoicedate();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvoicenumber($invoicenumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvoicenumber', [$invoicenumber]);

        return parent::setInvoicenumber($invoicenumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoicenumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoicenumber', []);

        return parent::getInvoicenumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompany($company)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompany', [$company]);

        return parent::setCompany($company);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompany()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompany', []);

        return parent::getCompany();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress1($address1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress1', [$address1]);

        return parent::setAddress1($address1);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress1', []);

        return parent::getAddress1();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress2($address2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress2', [$address2]);

        return parent::setAddress2($address2);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress2', []);

        return parent::getAddress2();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setPincode($pincode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPincode', [$pincode]);

        return parent::setPincode($pincode);
    }

    /**
     * {@inheritDoc}
     */
    public function getPincode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPincode', []);

        return parent::getPincode();
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', [$state]);

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', []);

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatecode($statecode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatecode', [$statecode]);

        return parent::setStatecode($statecode);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatecode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatecode', []);

        return parent::getStatecode();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobile($mobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobile', [$mobile]);

        return parent::setMobile($mobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobile', []);

        return parent::getMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setGstin($gstin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGstin', [$gstin]);

        return parent::setGstin($gstin);
    }

    /**
     * {@inheritDoc}
     */
    public function getGstin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGstin', []);

        return parent::getGstin();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubtotal($subtotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubtotal', [$subtotal]);

        return parent::setSubtotal($subtotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubtotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubtotal', []);

        return parent::getSubtotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCgst($cgst)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCgst', [$cgst]);

        return parent::setCgst($cgst);
    }

    /**
     * {@inheritDoc}
     */
    public function getCgst()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCgst', []);

        return parent::getCgst();
    }

    /**
     * {@inheritDoc}
     */
    public function setSgst($sgst)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSgst', [$sgst]);

        return parent::setSgst($sgst);
    }

    /**
     * {@inheritDoc}
     */
    public function getSgst()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSgst', []);

        return parent::getSgst();
    }

    /**
     * {@inheritDoc}
     */
    public function setIgst($igst)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIgst', [$igst]);

        return parent::setIgst($igst);
    }

    /**
     * {@inheritDoc}
     */
    public function getIgst()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIgst', []);

        return parent::getIgst();
    }

    /**
     * {@inheritDoc}
     */
    public function setCashdiscount($cashdiscount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCashdiscount', [$cashdiscount]);

        return parent::setCashdiscount($cashdiscount);
    }

    /**
     * {@inheritDoc}
     */
    public function getCashdiscount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCashdiscount', []);

        return parent::getCashdiscount();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrandtotal($grandtotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrandtotal', [$grandtotal]);

        return parent::setGrandtotal($grandtotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrandtotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrandtotal', []);

        return parent::getGrandtotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setBalance($balance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBalance', [$balance]);

        return parent::setBalance($balance);
    }

    /**
     * {@inheritDoc}
     */
    public function getBalance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBalance', []);

        return parent::getBalance();
    }

    /**
     * {@inheritDoc}
     */
    public function setInwords($inwords)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInwords', [$inwords]);

        return parent::setInwords($inwords);
    }

    /**
     * {@inheritDoc}
     */
    public function getInwords()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInwords', []);

        return parent::getInwords();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setCancel($cancel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCancel', [$cancel]);

        return parent::setCancel($cancel);
    }

    /**
     * {@inheritDoc}
     */
    public function getCancel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCancel', []);

        return parent::getCancel();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaiddate($paiddate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaiddate', [$paiddate]);

        return parent::setPaiddate($paiddate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaiddate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaiddate', []);

        return parent::getPaiddate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomer(\AppBundle\Entity\Customer $customer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomer', [$customer]);

        return parent::setCustomer($customer);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomer', []);

        return parent::getCustomer();
    }

}
