<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'grid.metadata.driver.annotation' shared service.

include_once $this->targetDirs[3].'\\vendor\\apy\\datagrid-bundle\\Grid\\Mapping\\Driver\\DriverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\apy\\datagrid-bundle\\Grid\\Mapping\\Driver\\Annotation.php';

return $this->services['grid.metadata.driver.annotation'] = new \APY\DataGridBundle\Grid\Mapping\Driver\Annotation(${($_ = isset($this->services['annotation_reader']) ? $this->services['annotation_reader'] : $this->getAnnotationReaderService()) && false ?: '_'});
