<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPnaypq1\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPnaypq1/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPnaypq1.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPnaypq1\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPnaypq1\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Pnaypq1',
    'container.build_id' => '6531c652',
    'container.build_time' => 1554210328,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPnaypq1');
