<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_ck_editor.form.type' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/AbstractType.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/ckeditor-bundle/src/Form/Type/CKEditorType.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/ckeditor-bundle/src/Model/ConfigManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/ckeditor-bundle/src/Model/ConfigManager.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/ckeditor-bundle/src/Model/PluginManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/ckeditor-bundle/src/Model/PluginManager.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/ckeditor-bundle/src/Model/StylesSetManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/ckeditor-bundle/src/Model/StylesSetManager.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/ckeditor-bundle/src/Model/TemplateManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/ckeditor-bundle/src/Model/TemplateManager.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/ckeditor-bundle/src/Model/ToolbarManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/ckeditor-bundle/src/Model/ToolbarManager.php';

return $this->services['fos_ck_editor.form.type'] = new \FOS\CKEditorBundle\Form\Type\CKEditorType(${($_ = isset($this->services['fos_ck_editor.config_manager']) ? $this->services['fos_ck_editor.config_manager'] : $this->services['fos_ck_editor.config_manager'] = new \FOS\CKEditorBundle\Model\ConfigManager()) && false ?: '_'}, ${($_ = isset($this->services['fos_ck_editor.plugin_manager']) ? $this->services['fos_ck_editor.plugin_manager'] : $this->services['fos_ck_editor.plugin_manager'] = new \FOS\CKEditorBundle\Model\PluginManager()) && false ?: '_'}, ${($_ = isset($this->services['fos_ck_editor.styles_set_manager']) ? $this->services['fos_ck_editor.styles_set_manager'] : $this->services['fos_ck_editor.styles_set_manager'] = new \FOS\CKEditorBundle\Model\StylesSetManager()) && false ?: '_'}, ${($_ = isset($this->services['fos_ck_editor.template_manager']) ? $this->services['fos_ck_editor.template_manager'] : $this->services['fos_ck_editor.template_manager'] = new \FOS\CKEditorBundle\Model\TemplateManager()) && false ?: '_'}, ${($_ = isset($this->services['fos_ck_editor.toolbar_manager']) ? $this->services['fos_ck_editor.toolbar_manager'] : $this->services['fos_ck_editor.toolbar_manager'] = new \FOS\CKEditorBundle\Model\ToolbarManager()) && false ?: '_'});
