<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'grid.manager' shared service.

include_once $this->targetDirs[3].'/vendor/apy/datagrid-bundle/Grid/GridManager.php';

return $this->services['grid.manager'] = new \APY\DataGridBundle\Grid\GridManager($this);
