<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'vich_uploader.upload_handler' shared service.

include_once $this->targetDirs[3].'/vendor/vich/uploader-bundle/Handler/AbstractHandler.php';
include_once $this->targetDirs[3].'/vendor/vich/uploader-bundle/Handler/UploadHandler.php';
include_once $this->targetDirs[3].'/vendor/vich/uploader-bundle/Injector/FileInjectorInterface.php';
include_once $this->targetDirs[3].'/vendor/vich/uploader-bundle/Injector/FileInjector.php';

$a = ${($_ = isset($this->services['vich_uploader.storage']) ? $this->services['vich_uploader.storage'] : $this->getVichUploader_StorageService()) && false ?: '_'};

return $this->services['vich_uploader.upload_handler'] = new \Vich\UploaderBundle\Handler\UploadHandler(${($_ = isset($this->services['vich_uploader.property_mapping_factory']) ? $this->services['vich_uploader.property_mapping_factory'] : $this->getVichUploader_PropertyMappingFactoryService()) && false ?: '_'}, $a, new \Vich\UploaderBundle\Injector\FileInjector($a), ${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'});
